name: Rust CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: Build
        run: cargo build --all --release
      - name: Run tests
        run: cargo test --all --release
      - name: List build artifacts
        run: ls -R target/release
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: fastproxy
          path: target/release/fastproxy
          if-no-files-found: error

  release:
    name: Release
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: fastproxy
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: fastproxy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
